### ISSUE TITLE
Migrate Profile

### ISSUE THREAD

**Issue by eag603** [isovera/icma#153]

**Comment by jardix22** [comment]
Now the Profiles are into the user profile. So, we need to migrate the users first. There are only 2 nodes, should they be migrated?

**Comment by amedina-icma** [comment]
I am unable to answers this question myself and have forwarded the issue onto to Bien and Fil.

**Comment by amedina-icma** [comment]
From Fil: "I don’t think you need to migrate over users? Users are created and their info is synced from netForum on login on the current site. Not sure if you plan to do this on the new site too?"

I do not think users need to be migrated because as Fil mentioned, the sync with NetForum creates users on Drupal.
