### ISSUE TITLE
Device testing: Homepage image alignment

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#357]
**Describe the bug**
on mobile, image alignment isn't the same (some images are flush left, some not, and some - liked the media video - seem to be right aligned)

**Screenshots**
<img width="292" alt="icma alignment iphonex" src="https://user-images.githubusercontent.com/31521411/110160575-30243380-7dba-11eb-84c0-51e1b97a8114.png">

**Smartphone (please complete the following information):**
 - Device: iphone x
 - Browser chrome

**Comment by hatuhay** [comment]
@eag603 
The video is inline-style, I fixed this before but was overriten.
The code for the video must be:
`<div class="embed-responsive embed-responsive-16by9"><iframe class="embed-responsive-item" allow="autoplay; encrypted-media" allowfullscreen="" frameborder="0" height="238" src="https://www.youtube.com/embed/videoseries?list=PLPuokMY5Tfipby8QdRhtjldq9EvJBp3wy" width="424"></iframe></div>`
Otherwise styles will be lost

**Comment by eag603** [comment]
@jardix22 can you help?

**Comment by jardix22** [comment]
@eag603 
Yes, I can do it.

**Comment by mnewberg1** [comment]
looks good to me, thanks!
