### ISSUE TITLE
Content Inclusion/Exclusion Requirements

### ISSUE THREAD

**Issue by eag603** [isovera/icma#370]
Andre provided the following list of rules for what content to include and not include. Can you please let me know if you have any questions and how much work this is?[https://app.zenhub.com/files/314661343/febf0620-9772-437d-adab-7ccb70adcac1/download](https://app.zenhub.com/files/314661343/febf0620-9772-437d-adab-7ccb70adcac1/download)

**Comment by jardix22** [comment]
@eag603, I have some questions

1. There are 5354 articles in the migration. So, in the file shared by Andre on the tab **Articles** there a list with only 201 nodes, which means that I should consider only them or just to be sure all those nodes should be migrated as part of the Broad rules?
2. The import of Landing pages should follow the same first abroad rule "Include all nodes with a [Post Date] of 1/1/20 to present"?

I think it will take around ~6h of work.

**Comment by jardix22** [comment]
Another questions:

1. If a **Basic Page** node was posted on 1/1/19 and its published state is yes, it should be ignored, right?
2. If an **Article** node was posted on 1/1/18 and it has the option checked "PM Subscriber Content", it should be ignored, right?

The cases "1" and "2" are ignored because they don't match the first rule ("Include all nodes with a [Post Date] of 1/1/20 to present"), right?

- If a **Basic Page** node was posted on 02/27/2017  and updated on 09/24/2020, It should be ignored or migrated?
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/a6d23d3a-f08e-4cd1-82bd-a28dd9a52e30)https://www.dropbox.com/s/0x8q5gkbpb8we60/affiliate_tag.png?dl=0

**Comment by eag603** [comment]
@jardix22 will need to revert some code already created in order to not implement these requirements per the client's request.
